sudo: False

language: python

matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6

install:
  # Install conda
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install dependencies
  - conda create -n test python=$TRAVIS_PYTHON_VERSION pytest
  - source activate test
  - conda install numpy pandas numba thriftpy python-snappy cython setuptools
  - pip install bson

script:
  - pip install -e .
  - py.test -x -vv --pyargs fastparquet

notifications:
  email: false
